//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace HOME
{


    public partial class Leaderboards
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new HOME.AdminMasterPage Master
        {
            get
            {
                Console.Write("hi");
                return ((HOME.AdminMasterPage)(base.Master));
            }
        }
    }
}
